follow_app/urls.py
from django.contrib import admin
from django.urls import path
from follow_app import views
from django.views.generic import TemplateView

app_name = 'followers'

urlpatterns = [
    path('', TemplateView.as_view(template_name='follower/follower.html'), name='index'),
    path("followthis/", views.followers.as_view(), name="followthis"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("join_us/", views.join_us, name="join_us")
]

upgrace/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('followers/', include('follow_app.urls')),
    path('likes/', include('like_app.urls')),
    path('comments/', include('comment_app.urls')),
    path('hashtags/', include('hashtag_app.urls')),
    url(r'^admin/', admin.site.urls),

    path('contact_us/', TemplateView.as_view(template_name="contact.html") ,name="contact_us"),
    path('how_it_works/', TemplateView.as_view(template_name="how_it_works.html") ,name="how_it_works"),
    path('about_us/', TemplateView.as_view(template_name="about.html") ,name="about_us"),
    path('', TemplateView.as_view(template_name="index.html") ,name="index"),
]

templates/follower/follower.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
{% csrf_token %}
<style>

    a:hover {
        text-decoration: none;
    }

    .progress {
        height: 30px;
        border-radius: 50px;
        background-color: rgba(225, 225, 225, 0.5);
    }

    .progress-bar {
        padding: 20px 0px;
        background-color: #ff253a;
    }

    .progress-bar h3 {
        font-size: 1.3rem;
        color: white;
        font-weight: 700;
        font-family: "Josefin Sans";
    }


    @media(max-width: 1200px) {
       
    }

    @media(max-width: 500px) {
        
    }

    @media(max-width: 1025px) {
        
    }

    .btn {
        background: linear-gradient(to right, #4A00E0, #8E2DE2);
        border: 2px solid white;
        border-radius: 50px;
        width: 150px;
        color: white;
        padding: 10px !important;
    }

    .btn:hover,
    .btn:focus {
        transition: ease 1s;
        border: 2px solid white;
        outline: none;
        color: black;
    }

    .btn:focus,
    .btn:active {
        outline: none !important;
        box-shadow: none;
    }

    
    .fc1 {
        border: 2px solid #4A00E0;
        width: 100%;
        height: 70px;
        color: #4A00E0;
        /* background: linear-gradient(to right, #4A00E0, #8E2DE2); */
        background: transparent;
    }

    .fc1::placeholder {
        color: #4A00E0;
        font-size: 1rem;
    }

    .form-group {
        background: transparent;
    }

    .fa {
        cursor: pointer;
    }

    .fa-chevron-down,
    .fa-chevron-up {
        color: #4A00E0;
    }

    .borderless td {
        border: none;
    }

    .btn-primary:hover {
        transition: all 0.3s ease-in-out;
        margin-top: -5px;
        color: white;
        box-shadow: 0px 0px 20px 0px rgb(173, 173, 173);
    }

    .sharenow_box {
        width: 25rem;
        padding: 20px 0px;
    }

    @media(max-width: 780px) {
        .sharenow_box {
            width: 18rem !important;
        }
    }

</style>

<script src="https://kit.fontawesome.com/ac520e76b0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>

<!--Main Part-->
<div class="share_now_con col-md-12 mx-auto text-center position-fixed" style="display: none; z-index: 2000;"
    data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
    <div class="card sharenow_box mx-auto text-center col-md-3"
        style="top: 150px; z-index: 2000; color: black; border-radius: 10px;">
        <div class="card-body mx-auto">
            <h1 style="color: rgb(85, 0, 255); font-weight: 700;" class="">Share It<br><h3>With Your Friends Now</h3></h1>
            <hr>    
            <div class="row" style="padding: 10px 0px 10px 0px;">
                <i onclick="shared_followers('whatsapp');" style="font-size: 3rem; color: green;"
                    class="mx-auto fab fa-whatsapp"></i>
                <i onclick="shared_followers('facebook');" style="font-size: 3rem; color: blue;"
                    class="mx-auto fab fa-facebook"></i>
                <i onclick="shared_followers('twitter');" style="font-size: 3rem; color: rgb(85, 207, 255);"
                    class="mx-auto fab fa-twitter"></i>
                <i onclick="shared_followers('linkedin');" style="font-size: 3rem; color: darkblue;"
                    class="mx-auto fab fa-linkedin"></i>
                <i onclick="shared_followers('link');" style="font-size: 3rem; color: blue;" data-clipboard-text="www.upgrace.in"
                    class="mx-auto fa fa-link copyit"></i>
            </div>
        </div>
        <div class="share_it_now" style="padding: 5px; display: none;">
            <p style="font-size: 20px; color: red;">Refresh The Page To Continue...</p>
        </div>
    </div>
    <script>
        new ClipboardJS('.copyit');
    </script>
</div>

<div class="try_other_con col-md-12 mx-auto text-center position-fixed" style="display: none; z-index: 2000;"
    data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50" style="background: transparent;">
    <div class="card sharenow_box mx-auto text-center"
        style="top: 50px; width: 20rem; z-index: 2000; color: black; border-radius: 5px;">
        <div class="card-body mx-auto">
            <h1 style="color: rgb(85, 0, 255); font-weight: 700;" class="">Try Our<br><h3>Other Free Services</h3></h1>
            <hr>    
            <div class="row" style="padding:0px 0px 0px 0px;">
                <a class="col mx-auto" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: red;"
                    class="mx-auto far fa-heart"></i>
                    <h6><br>Get<br>Likes</h6>
                </div></a>
                <a class="col mx-auto" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: rgb(0, 0, 0);"
                    class="mx-auto far fa-comments"></i>
                    <h6><br>Give<br>Comments</h6>
                </div></a>
                <a class="col mx-auto" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: rgb(36, 36, 36);"
                    class="mx-auto fas fa-hashtag"></i>
                    <h6><br>Generate<br>Hashtags</h6>
                </div></a>
            </div>
        </div>
    </div>
    <script>
        new ClipboardJS('.copyit');
    </script>
</div>

<div class="working_part fp mx-auto text-center justify-content-center"
    style="height: 300px; color: black; margin: 150px 0px 150px 0px; left: 0; position: relative; z-index: 9;"
    data-aos="fade-up" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
    <div class="col-sm-12 first_part mx-auto text-center">
        <h2 style="color: red;" class="error_txt"></h2>
        <form method="post" class="col-md-6 followers_form mx-auto text-center" style="top: 120px;">{% csrf_token %}
            <div class="form-group mr-auto text-left">
                <label for="uname"></label>
                <input required id="uname" name="username" style="padding: 25px; border-radius: 50px"
                    class="form-control fc1" type="text" placeholder="Type Your Insta Username" />
            </div>
            <br>
            <button type="submit" class="btn btn-primary">GetFollowers</button>
        </form>
    </div>
    <div class="col-sm-12 progress-part" style="left: 0; display: none">
        <h1 class="update_text"></h1>
        <div class="col-md-6 mx-auto text-center" style="padding: 40px;">
            <div class="progress">
                <div class="progress-bar progress-bar-striped active" id="myBar" role="progressbar" aria-valuenow="5"
                    aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <h3 class="progress-count"></h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 wantmore-part" style="left: 0; display: none;">
        <h1 style="color: #4A00E0; font-weight: 700;" class="you_got"></h1><br>
        <div class="col-md-7 mx-auto text-center" style="padding: 40px;">
            <h1>Want More Genuine Followers</h1><br>
            <button class="btn_more_followers btn btn-primary">
                <a style="color: white;" href="">Click Here</a></button>
        </div>
    </div>
</div>

<script>
    //Variables 
    var count = 0;
    var i = 0;
    var t = 0;
    var first_part = $('.first_part');
    var progress_part = $('.progress-part');
    var more_part = $('.wantmore-part');
    var ad_part = $('.ad-part');
    var updating = '';
    let text = ['Reached', 'Your account has been followed', 'Done'];
    // Main Part Function

    function share_now(){
        $('.working_part').hide();
        $('.share_now_con').fadeIn();
    }

    $(document).ready(function () {
        if(!!$.cookie('times_followers')){
            if (parseInt($.cookie('times_followers')) >= 19){
                $('.working_part').hide();
                $('.try_other_con').fadeIn();
                $.removeCookie('username');
                $.removeCookie('times_followers');
                $.removeCookie('url_followers');
            }
            else if (!!$.cookie('shared_followers')){
                $.removeCookie('shared_followers');
            }
            else{
                if(parseInt($.cookie('times_followers')) === 4 || parseInt($.cookie('times_followers')) === 9 || parseInt($.cookie('times_followers')) === 19){
                    share_now();
                }
                else{
                    
                }
            }
            $('#uname').val($.cookie('username_followers'));
        }
        else{
            $.cookie('times_followers', 0);
        }
    });

    $('.followers_form').on('submit', function (e) {
        e.preventDefault();

        $('.btn').prop("disabled", true);

        let form_data = $('#uname').val();
        var url_1 = 'https://www.instagram.com/' + form_data;
        $.cookie('username_followers', form_data, { expires: 1 });
        $.cookie('url_followers', url_1, { expires: 1 });
        
        container_works(first_part, progress_part);
        move();
        var updating = setInterval(changeText, 1000);
        $('.btn').prop("disabled", false);

        $.ajax({
            url: "{% url 'followers:followthis' %}",
            type: 'POST',
            data: {
                url_1: $.cookie('url_followers'),
                username: $.cookie('username_followers'),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (data) {
                if (data === 'Outdated'){
                    $('.working_part').hide();
                    $('.try_other_con').fadeIn();
                }
                else{
                    $('.you_got').html('');
                    $('.you_got').append(data);
                    container_works(progress_part, more_part);
                    if (!!$.cookie('times_followers')) {
                        $.cookie('times_followers', parseInt($.cookie('times_followers')) + 1);
                    }
                    else {
                        $.cookie('times_followers', 1, { expires: 1 });
                    }
                }
            },
            error: function (error) {
                console.log(error);
                container_works(progress_part, first_part);
                error_txt();
            }
        });
    });

    function error_txt() {
        $('.error_txt').html('');
        $('.error_txt').append('Network Problem. Please Try Again Later !!!')
    }

    function move() {
        if (i == 0) {
            i = 1;
            var elem = document.getElementById("myBar");
            var count = $(".progress-count");
            var width = 0;
            var id = setInterval(frame, 200);
            function frame() {
                if (width >= 100) {
                    count.html('');
                    count.html(width + "%");
                    clearInterval(id);
                    i = 0;
                } else {
                    count.html('');
                    count.html(width + "%");
                    width = parseInt(width) + 4;
                    elem.style.width = width + "%";
                }
            }
        }
    }

    function container_works(first_con, second_con) {
        first_con.fadeOut();
        second_con.fadeIn();
    }

    function show(cls) {
        cls.css({ 'display': 'block' });
    }

    function hide(cls) {
        cls.css({ 'display': 'none' });
    }

    function changeText() {
        if (count === 3) {
            clearInterval(updating);
        }
        else {
            $('.updated_text').fadeOut('slow');
            $(".update_text").html('<h3 class="updated_text" style="color: #4A00E0; font-weight: 700;">' + text[count] + '</h3>');
            setTimeout(function () {
                count < 3 ? count++ : count = 0;
            }, 500);
        }
    }

    function shared_followers(type) {
        $.cookie('shared_followers', 1, { expires: 1 });
        var whats_link = 'https://api.whatsapp.com/send?phone=0000000000&text=Get+genuine+popularity+on+instagram+now';
        var facebook_link = 'https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fupgrace+in';
        var linkedin_link = 'https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Fupgrace.in%2F&title=Get+Genuine+Popularity+Without+Password&summary=Tricks%2C+%2C+To+Get+Likes+Comments+Followers+Hashtags+For+Free.&source=UPGRACE.IN';
        var twitter_ink = 'https://twitter.com/intent/tweet?url=http%3A%2F%2Fupgrace.com%2F&text=Get+Genuine%2C+Popularity%2C+Without+Password.&hashtags=teenagers,memes,fans,fam';
        if (type == 'whatsapp') {
            window.open(whats_link, '_blank');
            $('.share_it_now').fadeIn();
        }
        else if (type == 'facebook') {
            window.open(facebook_link, '_blank');
            $('.share_it_now').fadeIn();
        }
        else if (type == 'twitter') {
            window.open(twitter_ink, '_blank');
            $('.share_it_now').fadeIn();
        }
        else if (type == 'linkedin') {
            window.open(linkedin_link, '_blank');
            $('.share_it_now').fadeIn();
        }
        else {
            $('.share_it_now').fadeIn();
        }
    }
</script>
{% endblock navbar %}