comment_app/urls.py
from django.contrib import admin
from django.urls import path
from comment_app import views
from django.views.generic import TemplateView

app_name = 'comments'

urlpatterns = [
    path('', TemplateView.as_view(template_name='comment/comment.html'), name='index'),
    path('commentit/', views.comments.as_view(), name='commentit'),
]

upgrace/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('followers/', include('follow_app.urls')),
    path('likes/', include('like_app.urls')),
    path('comments/', include('comment_app.urls')),
    path('hashtags/', include('hashtag_app.urls')),
    url(r'^admin/', admin.site.urls),

    path('contact_us/', TemplateView.as_view(template_name="contact.html") ,name="contact_us"),
    path('how_it_works/', TemplateView.as_view(template_name="how_it_works.html") ,name="how_it_works"),
    path('about_us/', TemplateView.as_view(template_name="about.html") ,name="about_us"),
    path('', TemplateView.as_view(template_name="index.html") ,name="index"),
]

templates/comment/comment.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
{% csrf_token %}
<style>

    a:hover {
        text-decoration: none;
    }

    .progress {
        height: 30px;
        border-radius: 50px;
        background-color: rgba(225, 225, 225, 0.5);
    }

    .progress-bar {
        padding: 20px 0px;
        background-color: #ff253a;
    }

    .progress-bar h3 {
        font-size: 1.3rem;
        color: white;
        font-weight: 700;
        font-family: "Josefin Sans";
    }


    @media(max-width: 1200px) {
       
    }

    @media(max-width: 500px) {
        
    }

    @media(max-width: 1025px) {
        
    }

    .btn {
        background: linear-gradient(to right, #4A00E0, #8E2DE2);
        border: 2px solid white;
        border-radius: 50px;
        width: 150px;
        color: white;
        padding: 10px !important;
    }

    .btn:hover,
    .btn:focus {
        transition: ease 1s;
        border: 2px solid white;
        outline: none;
        color: black;
    }

    .btn:focus,
    .btn:active {
        outline: none !important;
        box-shadow: none;
    }

    
    .fc1 {
        border: 2px solid #4A00E0;
        width: 100%;
        height: 70px;
        color: #4A00E0;
        /* background: linear-gradient(to right, #4A00E0, #8E2DE2); */
        background: transparent;
    }

    .fc1::placeholder {
        color: #4A00E0;
        font-size: 1rem;
    }

    .form-group {
        background: transparent;
    }

    .fa {
        cursor: pointer;
    }

    .fa-chevron-down,
    .fa-chevron-up {
        color: #4A00E0;
    }

    .borderless td {
        border: none;
    }

    .btn-primary:hover {
        transition: all 0.3s ease-in-out;
        margin-top: -5px;
        color: white;
        box-shadow: 0px 0px 20px 0px rgb(173, 173, 173);
    }

    .sharenow_box_comments {
        width: 25rem;
        padding: 20px 0px;
    }

    @media(max-width: 780px) {
        .sharenow_box_comments {
            width: 18rem !important;
        }
    }

</style>

<!--Main Comments Part-->
<div class="share_it_now_comments col-md-12 mx-auto text-center position-fixed" style="display: none; z-index: 2000;"
    data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
    <div class="card sharenow_box_comments mx-auto text-center col-md-3" style="top: 150px; z-index: 2000; color: black; border-radius: 10px;">
        <div class="card-body mx-auto">
            <h1 style="font-weight: bolder;">Share Now</h1>
            <hr>
            <div class="row" style="padding: 10px 0px 10px 0px;">
                <i onclick="shared_comments('whatsapp');" style="font-size: 2.3rem; color: green;" class="mx-auto fab fa-whatsapp"></i>
                <i onclick="shared_comments('facebook');" style="font-size: 2.3rem; color: blue;" class="mx-auto fab fa-facebook"></i>
                <i onclick="shared_comments('twitter');" style="font-size: 2.3rem; color: rgb(85, 207, 255);" class="mx-auto fab fa-twitter"></i>
                <i onclick="shared_comments('linkedin');" style="font-size: 2.3rem; color: darkblue;" class="mx-auto fab fa-linkedin"></i>
                <i onclick="shared_comments('link');" style="font-size: 2.3rem; color: blue;" data-clipboard-text="www.upgrace.in" class="mx-auto fa fa-link copyit"></i>
            </div>
        </div>
        <div class="share_it_hashtag" style="padding: 5px; display: none;">
            <p style="font-size: 20px; color: red;">Refresh The Page To Continue....</p>
        </div>
    </div>
    <script>
        new ClipboardJS('.copyurl');
    </script>
</div>

<div class="try_other_con col-md-12 mx-auto text-center position-fixed" style="display: none; z-index: 2000;"
    data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50" style="background: transparent;">
    <div class="card sharenow_box_comments mx-auto text-center"
        style="top: 50px; width: 20rem; z-index: 2000; color: black; border-radius: 5px;">
        <div class="card-body mx-auto">
            <h1 style="color: rgb(85, 0, 255); font-weight: 700;" class="">Try Our<br><h3>Other Free Services</h3></h1>
            <hr>    
            <div class="row" style="padding:0px 0px 0px 0px;">
                <a class="mx-auto col" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: red;"
                    class="mx-auto far fa-heart"></i>
                    <h6><br>Get<br>Likes</h6>
                </div></a>
                <a class="mx-auto col" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: rgb(0, 0, 0);"
                    class="mx-auto far fa-users"></i>
                    <h6><br>Give<br>Followers</h6>
                </div></a>
                <a class="mx-auto col" href=""><div class="mx-auto text-center">
                    <i style="font-size: 2.5rem; color: rgb(36, 36, 36);"
                    class="mx-auto fas fa-hashtag"></i>
                    <h6><br>Generate<br>Hashtags</h6>
                </div></a>
            </div>
        </div>
    </div>
</div>

<div class="fp mx-auto working_part_comments text-center justify-content-center"
    style="height: 300px; color: black; margin: 150px 0px 150px 0px; left: 0; position: relative; z-index: 9;"
    data-aos="fade-up" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
    <div class="col-sm-12 first_part mx-auto text-center">
        <h2 style="color: red;" class="error_txt"></h2>
        <form method="post" class="col-md-6 comments_form mx-auto text-center" style="top: 120px;">{% csrf_token %}
            <div class="form-group mr-auto text-left">
                <input required id="post_url_comments" name="username" style="padding: 25px; border-radius: 50px"
                    class="form-control fc1" type="text" placeholder="Type Your Post Url" /><br>
                <input id="comment_field" name="comment" style="padding: 20px; border-radius: 50px"
                    class="form-control fc1" type="text" placeholder="Type the comment you want to be posted" />
            </div>
            <br>
            <button type="submit" class="btn btn-primary">GetComments</button>
        </form>
    </div>
    <div class="col-sm-12 progress_part_comments" style="left: 0; display: none">
        <h1 class="update_text_comments"></h1>
        <div class="col-md-6 mx-auto text-center" style="padding: 40px;">
            <div class="progress">
                <div class="progress-bar progress-bar-striped active" id="myBar" role="progressbar" aria-valuenow="5"
                    aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <h3 class="progress-count"></h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 wantmore_part_comments" style="left: 0; display: none;">
        <h1 style="color: #4A00E0; font-weight: 700;" class="you_got_comments"></h1><br>
        <div class="col-md-7 mx-auto text-center" style="padding: 40px;">
            <h1>For More Genuine Comments</h1><br>
            <button class="btn_more_followers btn btn-primary">
                <a style="color: white !important;" href="">Click Here</a></button>
        </div>
    </div>
</div>

<script>
    //Variables 
    var uname = [
            'kalmesh.gpt123'
    ]
    var count = 0;
    var i = 0;
    var t = 0;
    var first_part = $('.first_part');
    var progress_part = $('.progress_part_comments');
    var more_part = $('.wantmore_part_comments');
    var ad_part = $('.ad-part');
    var updating = '';
    var take_this = '';
    let text = ['Reached', 'Your post just got a comment', 'Done'];

    function share_now(){
        $('.working_part_comments').hide();
        $('.share_now_comments').fadeIn();
    }

    function try_others(){
        $('.working_part_comments').hide();
        $('.try_other_con').fadeIn();
    }

    $(document).ready(function () {
        if(!!$.cookie('times_comments')){
            if (parseInt($.cookie('times_comments')) >= 19){
                try_others();
                $.removeCookie('comment');
                $.removeCookie('times_comments');
                $.removeCookie('url_comments');
            }
            else if (!!$.cookie('shared_comments')){
                $.removeCookie('shared_comments');
            }
            else{
                if(parseInt($.cookie('times_comments')) === 4 || parseInt($.cookie('times_comments')) === 9 || parseInt($.cookie('times_comments')) === 19){
                    console.log($.cookie('times_comments'));
                    share_now();
                }
                else{
                    
                }
            }
            $('#post_url_comments').val($.cookie('url_comments'));
            $('#comment_field').val($.cookie('comment'));
        }
        else{
            $.cookie('times_comments', 0);
        }
    });
    
    $('.comments_form').on('submit', function (e) {
        e.preventDefault();

        $('.btn').prop("disabled", true);
        

        let post_url_comments = $('#post_url_comments').val();
        let comment_field = $('#comment_field').val();
        $.cookie('url_comments', post_url_comments, { expires: 1 });
        $.cookie('comment', comment_field, { expires: 1 });
        
        container_works(first_part, progress_part);
        move();
        var updating = setInterval(changeText, 1000);
        var times_comments = parseInt($.cookie('times_comments'));
        var take_this = uname[times_comments];

        //not random
        // var take_this = uname[9];
        $('.btn').prop("disabled", false);
        
        $.ajax({
            url: "{% url 'comments:commentit' %}",
            type: "POST",
            data: {
                take_this_username: take_this,
                url_1: post_url_comments,
                comment: comment_field,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (data) {
                if (data === 'Outdated'){
                    $('.working_part_comments').hide();
                    $('.try_other_con').fadeIn();
                }
                else{
                    $('.you_got_comments').html('');
                    $('.you_got_comments').append(data);
                    container_works(progress_part, more_part);
                    if (!!$.cookie('times_comments')) {
                        $.cookie('times_comments', parseInt($.cookie('times_comments')) + 1);
                    }
                    else {
                        $.cookie('times_comments', 1);
                    }
                }
            },
            error: function (error) {
                console.log(error);
                container_works(progress_part, first_part);
                error_txt();
            }
        });
    });

    function error_txt() {
        $('.error_txt').html('');
        $('.error_txt').append('Network Problem. Please Try Again Later !!!')
    }

    function move() {
        if (i == 0) {
            i = 1;
            var elem = document.getElementById("myBar");
            var count = $(".progress-count");
            var width = 0;
            var id = setInterval(frame, 200);
            function frame() {
                if (width >= 100) {
                    count.html('');
                    count.html(width + "%");
                    clearInterval(id);
                    i = 0;
                } else {
                    count.html('');
                    count.html(width + "%");
                    width = parseInt(width) + 4;
                    elem.style.width = width + "%";
                }
            }
        }
    }

    function container_works(first_con, second_con) {
        first_con.fadeOut();
        second_con.fadeIn();
    }

    function show(cls) {
        cls.css({ 'display': 'block' });
    }

    function hide(cls) {
        cls.css({ 'display': 'none' });
    }

    function changeText() {
        if (parseInt(count) == 3) {
            clearInterval(updating);
        }
        else {
            $('.updated_text').fadeOut('slow');
            $(".update_text_comments").html('<h3 class="updated_text" style="color: #4A00E0; font-weight: 700;">' + text[count] + '</h3>');
            setTimeout(function () {
                count < 3 ? count++ : count = 0;
            }, 500);
        }
    }

    function shared_comments(type) {
        $.cookie('shared_comments', 1, { expires: 1 });
        var whats_link = 'https://api.whatsapp.com/send?phone=0000000000&text=Get+genuine+popularity+on+instagram+now';
        var facebook_link = 'https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fupgrace+in';
        var linkedin_link = 'https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Fupgrace.in%2F&title=Get+Genuine+Popularity+Without+Password&summary=Tricks%2C+%2C+To+Get+Likes+Comments+Followers+Hashtags+For+Free.&source=UPGRACE.IN';
        var twitter_ink = 'https://twitter.com/intent/tweet?url=http%3A%2F%2Fupgrace.com%2F&text=Get+Genuine%2C+Popularity%2C+Without+Password.&hashtags=teenagers,memes,fans,fam';
        if (type == 'whatsapp') {
            window.open(whats_link, '_blank');
            $('.share_it_now_comments').fadeIn();
        }
        else if (type == 'facebook') {
            window.open(facebook_link, '_blank');
            $('.share_it_now_comments').fadeIn();
        }
        else if (type == 'twitter') {
            window.open(twitter_ink, '_blank');
            $('.share_it_now_comments').fadeIn();
        }
        else if (type == 'linkedin') {
            window.open(linkedin_link, '_blank');
            $('.share_it_now_comments').fadeIn();
        }
        else {
            $('.share_it_now_comments').fadeIn();
        }
    }
</script>
{% endblock navbar %}