comment_app/urls.py
from django.contrib import admin
from django.urls import path
from comment_app import views
from django.views.generic import TemplateView

app_name = 'comments'

urlpatterns = [
    path('', TemplateView.as_view(template_name='comment/comment.html'), name='index'),
    path('commentit/', views.comments.as_view(), name='commentit'),
]

follow_app/urls.py
from django.contrib import admin
from django.urls import path
from follow_app import views
from django.views.generic import TemplateView

app_name = 'followers'

urlpatterns = [
    path('', TemplateView.as_view(template_name='follower/follower.html'), name='index'),
    path("followthis/", views.followers.as_view(), name="followthis"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("join_us/", views.join_us, name="join_us")
]

hashtag_app/urls.py
from django.contrib import admin
from django.urls import path
from hashtag_app import views
from django.views.generic import TemplateView

app_name = 'hashtags'

urlpatterns = [
    path('', TemplateView.as_view(template_name='hashtag/hashtag.html'), name='index'),
    path("fetch_hashtags/", views.generator.as_view(), name="generator")
]

like_app/urls.py
from django.contrib import admin
from django.urls import path
from like_app import views
from django.views.generic import TemplateView

app_name = 'likes'

urlpatterns = [
    path('', TemplateView.as_view(template_name='like/like.html'), name='index'),
    path("likeit/", views.likes.as_view(), name="likeit")
]

upgrace/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('followers/', include('follow_app.urls')),
    path('likes/', include('like_app.urls')),
    path('comments/', include('comment_app.urls')),
    path('hashtags/', include('hashtag_app.urls')),
    url(r'^admin/', admin.site.urls),

    path('contact_us/', TemplateView.as_view(template_name="contact.html") ,name="contact_us"),
    path('how_it_works/', TemplateView.as_view(template_name="how_it_works.html") ,name="how_it_works"),
    path('about_us/', TemplateView.as_view(template_name="about.html") ,name="about_us"),
    path('', TemplateView.as_view(template_name="index.html") ,name="index"),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<style>
    .gif_wrapper{
        padding: 30px;
        text-align: center !important;
    }
</style>
    <div class="col-md-12" style="margin: 100px 0px 100px 0px;" data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
        <div class="container mx-auto text-center" style="color: #4A00E0">
            <h1 style="font-weight: 900; color: #8E2DE2;">About Us</h1><Br>
            <br>
            <div class="row">
                <div class="col-md-6 mx-auto text-center">
                    <div class="gif_wrapper">
                        <img class="mx-auto text-center" style="max-width: 100%; height: 200px; display: block;" src="{% static 'logo/logo_white.jpg' %}" alt="">
                    </div>
                </div>
                <div class="col-md-6 mx-auto text-left" style="margin-top: 40px;">
                    <p><a href="{% url 'index' %}">Upgrace.in</a> runs by an individual person who's name is not revealed yet,
                        but his mission is all about helping teenagers, developers and working class peoples
                        to make their work free, fast and simple.<br><Br>
                        He is continuosly working hard on creating new types of web apps which can speed up our works.<Br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If you peoples want to contribute on his journey then you're open to do so. <a href="#join_us">JOIN HERE</a> </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<style>
    .gif_wrapper{
        padding: 30px;
        text-align: center !important;
    }
    td, tr{
        border: none !important;
    }
</style>
    <div class="col-md-12" style="margin: 100px 0px 100px 0px;" data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
        <div class="container mx-auto text-center" style="color: #4A00E0">
            <h1 style="font-weight: 900; color: #8E2DE2;">Contact Us</h1><Br>
            <br>
            <div class="row">
                <div class="col-md-6" style="margin-top: 50px;">
                    <div class="mx-auto text-center table-responsive">
                        <table class="table">
                            <tr>
                                <td><i style="font-size: 1.5rem;" class="fas fa-phone-alt"></i></td>
                                <td>+1 213-861-9313</td>
                            </tr>
                            <tr>
                                <td><i style="font-size: 1.5rem;" class="far fa-envelope"></i></td>
                                <td>upgrace.in@gmail.com</td>
                            </tr>
                            <tr>
                                <td><i style="font-size: 1.5rem;" class="fas fa-map-marker-alt"></i></td>
                                <td>2943  Farnum Road, New York</td>
                            </tr>
                        </table>    
                    </div>
                </div>
                <form action="{% url 'followers:contact_us' %}" method="POST" class="col-md-6 ml-auto text-right">
                    <div class="row">{% csrf_token %}
                        <div class="form-group col-md-6">
                            <label for="field_name"></label>
                            <input type="text" name="field_name" id="field_name" class="form-control" placeholder="Your Name">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="field_email"></label>
                            <input type="email" name="field_email" id="field_email" class="form-control" placeholder="Your Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="field_sub"></label>
                        <input type="text" name="subject" id="field_sub" class="form-control" placeholder="Subject">
                    </div>
                    <div class="form-group">
                        <textarea name="msg" id="field_msg" rows="5" class="form-control" placeholder="Your Message..."></textarea>
                    </div>
                    <div class="mx-auto text-center">
                        <button type="submit" class="mx-auto text-center btn btn-primary">Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/how_it_works.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<style>
    .gif_wrapper{
        padding: 30px;
        text-align: center !important;
    }
</style>
    <div class="col-md-12" style="margin: 100px 0px 100px 0px;" data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
        <div class="container mx-auto text-center" style="color: #4A00E0">
            <h1 style="font-weight: 900; color: #8E2DE2;">How It Works</h1><Br>
            <p>It works "For The People & By The People". Individuals who want to meet as well as rise expertise through our network
                Join Us. <Br>
                &nbsp;&nbsp;&nbsp;&nbsp;We with our technology & support help them via originating a chain of network on this gloal
                world.<Br>
                They get all tpes of rights and supports related to our services as follows :
            </p>
            <br>
            <div class="wrapper">
                <div class="row">
                    <div class="gif_wrapper col-sm-3">
                        <p style="color: #4A00E0;">Originate FanBase</p>
                        <a target="_blank" href="{% static 'gifs/followers.gif' %}"><img style="max-width: 100%; height: auto; display: block;" src="{% static 'gifs/followers.gif' %}" alt=""></a>
                    </div>
                    <div class="gif_wrapper col-sm-3">
                        <p style="color: rgb(255, 0, 0);">Generate Likes</p>
                        <a target="_blank" href="{% static 'gifs/likes.gif' %}"><img style="max-width: 100%; height: auto; display: block;" src="{% static 'gifs/likes.gif' %}" alt=""></a>
                    </div>
                    <div class="gif_wrapper col-sm-3">
                        <p style="color: rgb(126, 126, 126);">Fetch Hashtags</p>
                        <a target="_blank" href="{% static 'gifs/hashtags.gif' %}"><img style="max-width: 100%; height: auto; display: block;" src="{% static 'gifs/hashtags.gif' %}" alt=""></a>
                    </div>
                    <div class="gif_wrapper col-sm-3">
                        <p style="color: rgb(0, 0, 0);">Create Comments</p>
                        <a target="_blank" href="{% static 'gifs/comments.gif' %}"><img style="max-width: 100%; height: auto; display: block;" src="{% static 'gifs/comments.gif' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block navbar %}
    <div class="col-md-12" style="margin: 100px 0px 150px 0px;" data-aos="fade-down" data-aos-offset="200" data-aos-duration="1000" data-aos-delay="50">
        <div class="col-md-6 mx-auto text-center">
            <div class="card-body mx-auto">
                <h1 style="color: #8E2DE2; font-weight: 600;" class="">Our Services</h1><Br>
                <hr>    
                <div class="row" style="margin-top: 30px;">
                    <a style="margin-top: 30px; color: rgb(255, 0, 0); font-weight: 700 !important;" target="_blank" class="mx-auto col-md-3" href="{% url 'likes:index' %}">
                        <div class="mx-auto text-center">
                            <i style="font-size: 2.5rem; color: rgb(255, 0, 0);"
                            class="mx-auto far fa-heart"></i>
                            <h6><br>Generate<br>Likes</h6>
                        </div>
                    </a>
                    <a style="margin-top: 30px; color: #4A00E0; font-weight: 700 !important;" target="_blank" class="mx-auto col-md-3" href="{% url 'followers:index' %}">
                        <div class="mx-auto text-center">
                            <i style="font-size: 2.5rem; color: #4A00E0;"
                            class="mx-auto fas fa-users"></i>
                            <h6><br>Originate<br>FanBase</h6>
                        </div>
                    </a>
                    <a style="margin-top: 30px; color: rgb(126, 126, 126); font-weight: 700 !important;" target="_blank" class="mx-auto col-md-3" href="{% url 'hashtags:index' %}">
                        <div class="mx-auto text-center">
                            <i style="font-size: 2.5rem; color: rgb(126, 126, 126);"
                            class="mx-auto fas fa-hashtag"></i>
                            <h6><br>Fetch<br>Hashtags</h6>
                        </div>
                    </a>
                    <a style="margin-top: 30px; color: rgb(0, 0, 0); font-weight: 700 !important;" target="_blank" class="mx-auto col-md-3" href="{% url 'comments:index' %}">
                        <div class="mx-auto text-center">
                            <i style="font-size: 2.5rem; color: rgb(0, 0, 0);"
                            class="mx-auto fas fa-comments"></i>
                            <h6><br>Create<br>Comments</h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}